-- BIANTI - Stock, importacion masiva de ventas, eliminacion masiva y portadas.
-- Ejecutar manualmente desde Supabase SQL Editor. No ejecutar desde el frontend.

create extension if not exists pgcrypto with schema extensions;

alter table public.categorias
  add column if not exists portada_url text;

create table if not exists public.ventas_importaciones (
  id bigint generated by default as identity primary key,
  archivo_sha256 text not null unique,
  origen text not null default 'importacion_csv',
  usuario_id integer,
  filas integer not null default 0,
  unidades integer not null default 0,
  total numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.ventas_importacion_items (
  id bigint generated by default as identity primary key,
  importacion_id bigint not null references public.ventas_importaciones(id) on delete cascade,
  fila integer not null,
  producto_id bigint not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(14,2) not null check (precio_unitario > 0),
  total numeric(14,2) not null,
  fecha date not null,
  observacion text,
  cliente text,
  medio_pago text,
  venta_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists ventas_importacion_items_importacion_idx on public.ventas_importacion_items(importacion_id);
create index if not exists ventas_importacion_items_producto_idx on public.ventas_importacion_items(producto_id);
create index if not exists ventas_importaciones_hash_idx on public.ventas_importaciones(archivo_sha256);
create index if not exists productos_stock_actual_idx on public.productos(stock_actual);

create or replace function public._bianti_admin_usuario(p_token text)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_usuario_id integer;
begin
  if coalesce(p_token, '') = '' then
    raise exception 'Token administrativo requerido';
  end if;

  delete from public.admin_sessions where expires_at <= now();

  select s.usuario_id
    into v_usuario_id
  from public.admin_sessions s
  join public.usuarios u on u.id = s.usuario_id
  where s.expires_at > now()
    and u.activo is true
    and s.token_hash = encode(extensions.digest(p_token, 'sha256'), 'hex')
  limit 1;

  if v_usuario_id is null then
    raise exception 'Sesion administrativa invalida';
  end if;

  return v_usuario_id;
end;
$$;

create or replace function public.importar_ventas_masivas(p_token text, p_archivo_sha256 text, p_filas jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_usuario_id integer;
  v_importacion_id bigint;
  v_row jsonb;
  v_producto_id bigint;
  v_cantidad integer;
  v_precio numeric(14,2);
  v_fecha date;
  v_total numeric(14,2);
  v_stock integer;
  v_venta_id bigint;
  v_unidades integer := 0;
  v_importe numeric(14,2) := 0;
  v_total_producto record;
begin
  v_usuario_id := public._bianti_admin_usuario(p_token);

  if coalesce(p_archivo_sha256, '') = '' then
    raise exception 'Hash de archivo requerido';
  end if;

  if exists (select 1 from public.ventas_importaciones where archivo_sha256 = p_archivo_sha256) then
    raise exception 'Este archivo CSV ya fue importado';
  end if;

  if jsonb_typeof(p_filas) <> 'array' or jsonb_array_length(p_filas) = 0 then
    raise exception 'No hay filas para importar';
  end if;

  create temporary table tmp_importar_ventas (
    fila integer,
    producto_id bigint,
    cantidad integer,
    precio_unitario numeric(14,2),
    fecha date,
    observacion text,
    cliente text,
    medio_pago text
  ) on commit drop;

  for v_row in select * from jsonb_array_elements(p_filas) loop
    v_producto_id := nullif(v_row->>'producto_id', '')::bigint;
    v_cantidad := nullif(v_row->>'cantidad', '')::integer;
    v_precio := nullif(v_row->>'precio_unitario', '')::numeric(14,2);
    v_fecha := nullif(v_row->>'fecha', '')::date;

    if v_producto_id is null or v_cantidad is null or v_cantidad <= 0 or v_precio is null or v_precio <= 0 or v_fecha is null then
      raise exception 'Fila invalida en importacion: %', coalesce(v_row->>'fila', '?');
    end if;

    insert into tmp_importar_ventas (fila, producto_id, cantidad, precio_unitario, fecha, observacion, cliente, medio_pago)
    values ((v_row->>'fila')::integer, v_producto_id, v_cantidad, v_precio, v_fecha, nullif(v_row->>'observacion', ''), nullif(v_row->>'cliente', ''), nullif(v_row->>'medio_pago', ''));
  end loop;

  for v_total_producto in select producto_id, sum(cantidad)::integer as cantidad from tmp_importar_ventas group by producto_id loop
    select stock_actual
      into v_stock
    from public.productos
    where id = v_total_producto.producto_id
    for update;

    if not found then
      raise exception 'Producto inexistente: %', v_total_producto.producto_id;
    end if;

    if v_stock is null or v_stock < v_total_producto.cantidad then
      raise exception 'Stock insuficiente para producto %', v_total_producto.producto_id;
    end if;
  end loop;

  insert into public.ventas_importaciones (archivo_sha256, origen, usuario_id, filas, unidades, total)
  values (p_archivo_sha256, 'importacion_csv', v_usuario_id, 0, 0, 0)
  returning id into v_importacion_id;

  for v_row in select to_jsonb(t) from tmp_importar_ventas t order by t.fila loop
    v_producto_id := (v_row->>'producto_id')::bigint;
    v_cantidad := (v_row->>'cantidad')::integer;
    v_precio := (v_row->>'precio_unitario')::numeric(14,2);
    v_fecha := (v_row->>'fecha')::date;
    v_total := round(v_cantidad * v_precio, 2);

    insert into public.ventas (producto_id, cantidad, precio, total, fecha)
    values (v_producto_id, v_cantidad, v_precio, v_total, v_fecha)
    returning id into v_venta_id;

    insert into public.ventas_importacion_items (importacion_id, fila, producto_id, cantidad, precio_unitario, total, fecha, observacion, cliente, medio_pago, venta_id)
    values (v_importacion_id, (v_row->>'fila')::integer, v_producto_id, v_cantidad, v_precio, v_total, v_fecha, nullif(v_row->>'observacion', ''), nullif(v_row->>'cliente', ''), nullif(v_row->>'medio_pago', ''), v_venta_id);

    v_unidades := v_unidades + v_cantidad;
    v_importe := v_importe + v_total;
  end loop;

  update public.productos p
  set stock_actual = p.stock_actual - t.cantidad
  from (select producto_id, sum(cantidad)::integer as cantidad from tmp_importar_ventas group by producto_id) t
  where p.id = t.producto_id
    and p.stock_actual - t.cantidad >= 0;

  if exists (
    select 1
    from public.productos p
    join (select producto_id, sum(cantidad)::integer as cantidad from tmp_importar_ventas group by producto_id) t on t.producto_id = p.id
    where p.stock_actual < 0
  ) then
    raise exception 'La importacion generaria stock negativo';
  end if;

  update public.ventas_importaciones
  set filas = (select count(*) from tmp_importar_ventas), unidades = v_unidades, total = v_importe
  where id = v_importacion_id;

  return jsonb_build_object('ok', true, 'importacion_id', v_importacion_id, 'unidades', v_unidades, 'total', v_importe);
end;
$$;

create or replace function public.previsualizar_eliminacion_productos_masiva(p_token text, p_producto_ids text[])
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_usuario_id integer;
  v_storage_paths text[] := '{}';
  v_result jsonb;
begin
  v_usuario_id := public._bianti_admin_usuario(p_token);

  if p_producto_ids is null or array_length(p_producto_ids, 1) is null then
    raise exception 'No se recibieron productos';
  end if;

  drop table if exists tmp_eliminar_productos_preview;
  create temporary table tmp_eliminar_productos_preview (id bigint primary key) on commit drop;
  insert into tmp_eliminar_productos_preview (id)
  select distinct unnest(p_producto_ids)::bigint;

  select coalesce(array_agg(path), '{}') into v_storage_paths
  from (
    select url as path from public.producto_fotos f join tmp_eliminar_productos_preview t on t.id = f.producto_id where nullif(url, '') is not null
    union
    select portada_url as path from public.productos p join tmp_eliminar_productos_preview t on t.id = p.id where nullif(portada_url, '') is not null
  ) s;

  select jsonb_build_object(
    'cantidad_productos', (select count(*) from public.productos p join tmp_eliminar_productos_preview t on t.id = p.id),
    'inexistentes', coalesce((select jsonb_agg(t.id) from tmp_eliminar_productos_preview t left join public.productos p on p.id = t.id where p.id is null), '[]'::jsonb),
    'productos', coalesce((select jsonb_agg(jsonb_build_object('id', p.id, 'titulo', p.titulo, 'portada_url', p.portada_url)) from public.productos p join tmp_eliminar_productos_preview t on t.id = p.id), '[]'::jsonb),
    'fotos', (select count(*) from public.producto_fotos f join tmp_eliminar_productos_preview t on t.id = f.producto_id),
    'talles', (select count(*) from public.producto_talles pt join tmp_eliminar_productos_preview t on t.id = pt.producto_id),
    'categorias', (select count(*) from public.producto_categorias pc join tmp_eliminar_productos_preview t on t.id = pc.producto_id),
    'variantes', (select count(*) from public.variantes v join tmp_eliminar_productos_preview t on t.id = v.producto_id),
    'eventos', (select count(*) from public.eventos e join tmp_eliminar_productos_preview t on coalesce(e.payload::jsonb->>'producto_id', e.payload::jsonb->>'product_id', e.payload::jsonb->>'id') = t.id::text),
    'vistas', (select count(*) from public.eventos e join tmp_eliminar_productos_preview t on coalesce(e.payload::jsonb->>'producto_id', e.payload::jsonb->>'product_id', e.payload::jsonb->>'id') = t.id::text where e.type in ('view_product', 'product_view', 'producto_visto')),
    'clicks', (select count(*) from public.eventos e join tmp_eliminar_productos_preview t on coalesce(e.payload::jsonb->>'producto_id', e.payload::jsonb->>'product_id', e.payload::jsonb->>'id') = t.id::text where e.type in ('whatsapp_click', 'click_whatsapp', 'whatsapp') or e.type ilike '%whatsapp%'),
    'pedidos', (select count(*) from public.pedidos pe join tmp_eliminar_productos_preview t on t.id = pe.producto_id),
    'pedido_items', (select count(*) from public.pedido_items pi join tmp_eliminar_productos_preview t on t.id = pi.producto_id),
    'ventas', (select count(*) from public.ventas v join tmp_eliminar_productos_preview t on t.id = v.producto_id),
    'ventas_manuales', (select count(*) from public.ventas_manuales vm join tmp_eliminar_productos_preview t on t.id = vm.producto_id),
    'unidades_vendidas', coalesce((select sum(cantidad) from public.ventas v join tmp_eliminar_productos_preview t on t.id = v.producto_id), 0) + coalesce((select sum(cantidad) from public.ventas_manuales vm join tmp_eliminar_productos_preview t on t.id = vm.producto_id), 0),
    'importe_ventas', coalesce((select sum(coalesce(total, precio * cantidad)) from public.ventas v join tmp_eliminar_productos_preview t on t.id = v.producto_id), 0) + coalesce((select sum(coalesce(total, precio_final * cantidad)) from public.ventas_manuales vm join tmp_eliminar_productos_preview t on t.id = vm.producto_id), 0),
    'storage_paths', to_jsonb(v_storage_paths)
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.eliminar_productos_masivo(p_token text, p_producto_ids text[], p_modo text default 'total')
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_usuario_id integer;
  v_storage_paths text[] := '{}';
  v_preview jsonb;
begin
  v_usuario_id := public._bianti_admin_usuario(p_token);

  if p_producto_ids is null or array_length(p_producto_ids, 1) is null then
    raise exception 'No se recibieron productos';
  end if;

  drop table if exists tmp_eliminar_productos;
  create temporary table tmp_eliminar_productos (id bigint primary key) on commit drop;
  insert into tmp_eliminar_productos (id)
  select distinct unnest(p_producto_ids)::bigint;

  perform 1 from public.productos p join tmp_eliminar_productos t on t.id = p.id for update;

  v_preview := public.previsualizar_eliminacion_productos_masiva(p_token, p_producto_ids);
  select coalesce(array_agg(path), '{}') into v_storage_paths
  from jsonb_array_elements_text(coalesce(v_preview->'storage_paths', '[]'::jsonb)) as x(path);

  delete from public.ventas_importacion_items i using tmp_eliminar_productos t where i.producto_id = t.id;
  delete from public.ventas v using tmp_eliminar_productos t where v.producto_id = t.id;
  delete from public.ventas_manuales vm using tmp_eliminar_productos t where vm.producto_id = t.id;
  delete from public.pedido_items pi using tmp_eliminar_productos t where pi.producto_id = t.id;
  delete from public.pedidos pe using tmp_eliminar_productos t where pe.producto_id = t.id;

  delete from public.eventos e
  using tmp_eliminar_productos t
  where coalesce(e.payload::jsonb->>'producto_id', e.payload::jsonb->>'product_id', e.payload::jsonb->>'id') = t.id::text;

  delete from public.producto_fotos f using tmp_eliminar_productos t where f.producto_id = t.id;
  delete from public.producto_talles pt using tmp_eliminar_productos t where pt.producto_id = t.id;
  delete from public.producto_categorias pc using tmp_eliminar_productos t where pc.producto_id = t.id;
  delete from public.variantes v using tmp_eliminar_productos t where v.producto_id = t.id;

  delete from public.productos p using tmp_eliminar_productos t where p.id = t.id;

  return v_preview || jsonb_build_object('ok', true, 'modo', 'total', 'storage_paths', to_jsonb(v_storage_paths));
end;
$$;

revoke all on function public._bianti_admin_usuario(text) from public;
revoke all on function public.importar_ventas_masivas(text, text, jsonb) from public;
revoke all on function public.previsualizar_eliminacion_productos_masiva(text, text[]) from public;
revoke all on function public.eliminar_productos_masivo(text, text[], text) from public;

grant execute on function public.importar_ventas_masivas(text, text, jsonb) to anon;
grant execute on function public.previsualizar_eliminacion_productos_masiva(text, text[]) to anon;
grant execute on function public.eliminar_productos_masivo(text, text[], text) to anon;

alter table public.ventas_importaciones enable row level security;
alter table public.ventas_importacion_items enable row level security;

revoke all on table public.ventas_importaciones from anon;
revoke all on table public.ventas_importacion_items from anon;
