<section class="page-head"><div><h1>Productos</h1><p>Buscar, filtrar y administrar productos usando la misma base de Supabase.</p></div><div class="page-actions"><a class="btn primary" href="<?= site_url('admin/productos/nuevo') ?>">Nuevo producto</a><a class="btn outline" href="<?= site_url('admin/importar-productos') ?>">Importar</a></div></section>
<?php if(!empty($error)): ?><div class="alert error"><?= e($error) ?></div><?php endif; ?>
<form class="filter-admin" method="get">
  <input name="q" value="<?= e($_GET['q'] ?? '') ?>" placeholder="Buscar por título o categoría...">
  <select name="categoria"><option value="">Todas las categorías</option><?php foreach($categorias as $c): ?><option value="<?= e($c['id']) ?>" <?= (string)($_GET['categoria']??'')===(string)$c['id']?'selected':'' ?>><?= e($c['nombre']) ?></option><?php endforeach; ?></select>
  <select name="visible"><option value="">Visible y oculto</option><option value="1" <?= ($_GET['visible']??'')==='1'?'selected':'' ?>>Visibles</option><option value="0" <?= ($_GET['visible']??'')==='0'?'selected':'' ?>>Ocultos</option></select>
  <select name="disponible"><option value="">Todas las disponibilidades</option><option value="1" <?= ($_GET['disponible']??'')==='1'?'selected':'' ?>>Disponibles</option><option value="0" <?= ($_GET['disponible']??'')==='0'?'selected':'' ?>>No disponibles</option></select>
  <select name="foto"><option value="">Con y sin foto</option><option value="1" <?= ($_GET['foto']??'')==='1'?'selected':'' ?>>Con foto</option><option value="0" <?= ($_GET['foto']??'')==='0'?'selected':'' ?>>Sin foto</option></select>
  <select name="sort"><option value="recientes">Más recientes</option><option value="precio_asc" <?= ($_GET['sort']??'')==='precio_asc'?'selected':'' ?>>Precio menor</option><option value="precio_desc" <?= ($_GET['sort']??'')==='precio_desc'?'selected':'' ?>>Precio mayor</option><option value="titulo_asc" <?= ($_GET['sort']??'')==='titulo_asc'?'selected':'' ?>>Nombre A-Z</option></select>
  <button class="btn primary">Filtrar</button><a class="btn outline" href="<?= site_url('admin/productos') ?>">Limpiar</a>
</form>
<div class="panel"><div class="table-responsive"><table class="admin-table"><thead><tr><th>Foto</th><th>ID</th><th>Producto</th><th>Categorías</th><th>Talles</th><th>Precio</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($productos as $p): ?><tr><td><img class="thumb" src="<?= e($p['portada'] ?: asset_url('img/logo.png')) ?>" alt=""></td><td>#<?= e($p['id']) ?></td><td><strong><?= e($p['titulo'] ?? '-') ?></strong><small><?= e(mb_strimwidth($p['descripcion'] ?? '',0,80,'...')) ?></small></td><td><?php foreach(($p['categorias'] ?: ['Sin categoría']) as $cat): ?><span class="chip strong"><?= e($cat) ?></span><?php endforeach; ?></td><td><?php foreach(($p['talles'] ?: ['-']) as $talle): ?><span class="badge-soft"><?= e($talle) ?></span><?php endforeach; ?></td><td><?= money_ar($p['precio_final'] ?? $p['precio_venta'] ?? $p['precio'] ?? 0) ?></td><td><span class="state <?= !empty($p['visible'])?'ok':'warn' ?>"><?= !empty($p['visible'])?'Visible':'Oculto' ?></span><span class="state <?= !empty($p['disponible'])?'ok':'bad' ?>"><?= !empty($p['disponible'])?'Disponible':'No disponible' ?></span></td><td><div class="actions"><a class="btn small" href="<?= site_url('admin/productos/editar/'.$p['id']) ?>">Editar</a><form method="post" action="<?= site_url('admin/productos/toggle/'.$p['id']) ?>"><?= csrf_field() ?><input type="hidden" name="field" value="visible"><input type="hidden" name="value" value="<?= !empty($p['visible'])?'0':'1' ?>"><button class="btn small"><?= !empty($p['visible'])?'Ocultar':'Mostrar' ?></button></form><form method="post" action="<?= site_url('admin/productos/toggle/'.$p['id']) ?>"><?= csrf_field() ?><input type="hidden" name="field" value="disponible"><input type="hidden" name="value" value="<?= !empty($p['disponible'])?'0':'1' ?>"><button class="btn small"><?= !empty($p['disponible'])?'No disp.':'Disponible' ?></button></form><form method="post" action="<?= site_url('admin/productos/eliminar/'.$p['id']) ?>" onsubmit="return confirm('¿Eliminar este producto?')"><?= csrf_field() ?><button class="btn small">Eliminar</button></form></div></td></tr><?php endforeach; ?></tbody></table></div>
<div class="product-admin-cards"><?php foreach($productos as $p): ?><article class="admin-product-card"><img src="<?= e($p['portada'] ?: asset_url('img/logo.png')) ?>" alt=""><div><span class="muted">#<?= e($p['id']) ?></span><h3><?= e($p['titulo'] ?? '-') ?></h3><strong><?= money_ar($p['precio_final'] ?? $p['precio_venta'] ?? $p['precio'] ?? 0) ?></strong><div><?php foreach(($p['categorias'] ?: ['Sin categoría']) as $cat): ?><span class="chip strong"><?= e($cat) ?></span><?php endforeach; ?></div><div><span class="state <?= !empty($p['visible'])?'ok':'warn' ?>"><?= !empty($p['visible'])?'Visible':'Oculto' ?></span><span class="state <?= !empty($p['disponible'])?'ok':'bad' ?>"><?= !empty($p['disponible'])?'Disponible':'No disponible' ?></span></div><details><summary>Acciones</summary><a class="btn small" href="<?= site_url('admin/productos/editar/'.$p['id']) ?>">Editar</a><form method="post" action="<?= site_url('admin/productos/toggle/'.$p['id']) ?>"><?= csrf_field() ?><input type="hidden" name="field" value="visible"><input type="hidden" name="value" value="<?= !empty($p['visible'])?'0':'1' ?>"><button class="btn small"><?= !empty($p['visible'])?'Ocultar':'Mostrar' ?></button></form><form method="post" action="<?= site_url('admin/productos/toggle/'.$p['id']) ?>"><?= csrf_field() ?><input type="hidden" name="field" value="disponible"><input type="hidden" name="value" value="<?= !empty($p['disponible'])?'0':'1' ?>"><button class="btn small"><?= !empty($p['disponible'])?'No disponible':'Disponible' ?></button></form><form method="post" action="<?= site_url('admin/productos/eliminar/'.$p['id']) ?>" onsubmit="return confirm('¿Eliminar este producto?')"><?= csrf_field() ?><button class="btn small">Eliminar</button></form></details></div></article><?php endforeach; ?></div></div>
