<?php
$views=array_filter($eventos,fn($e)=>($e['type']??'')==='view_product');$wa=array_filter($eventos,fn($e)=>($e['type']??'')==='click_whatsapp');$catsEv=array_filter($eventos,fn($e)=>($e['type']??'')==='view_category');
$productMap=[]; foreach($productos as $p)$productMap[(string)$p['id']]=$p;
$top=[]; foreach($views as $e){$payload=is_array($e['payload']??null)?$e['payload']:json_decode((string)($e['payload']??'{}'),true);$id=(string)($payload['producto_id']??''); if($id!=='')$top[$id]=($top[$id]??0)+1;} arsort($top); $max=max($top?:[1]);
$waTop=[]; foreach($wa as $e){$payload=is_array($e['payload']??null)?$e['payload']:json_decode((string)($e['payload']??'{}'),true);$id=(string)($payload['producto_id']??''); if($id!=='')$waTop[$id]=($waTop[$id]??0)+1;} arsort($waTop);
?>
<section class="page-head"><div><h1>Métricas</h1><p>Actividad real del catálogo: imagen, producto, categoría, clics y consultas WhatsApp.</p></div></section>
<div class="kpi-grid"><div class="kpi"><span>Vistas de productos</span><strong><?= count($views) ?></strong></div><div class="kpi"><span>Clicks WhatsApp</span><strong><?= count($wa) ?></strong></div><div class="kpi"><span>Categorías vistas</span><strong><?= count($catsEv) ?></strong></div><div class="kpi"><span>Eventos totales</span><strong><?= count($eventos) ?></strong></div></div>
<div class="chart-panel"><div class="panel"><h2>Top productos por interés</h2><?php if(!$top): ?><p class="muted">No hay datos suficientes todavía.</p><?php endif; ?><?php foreach(array_slice($top,0,10,true) as $id=>$count): $p=$productMap[$id]??[]; $cat=($p['categorias'][0]??'Sin categoría'); ?><div class="bar-row product-metric"><img src="<?= e($p['portada'] ?? asset_url('img/logo.png')) ?>" alt=""><span><?= e($p['titulo'] ?? ('Producto #'.$id)) ?><small>#<?= e($id) ?> · <?= e($cat) ?></small></span><div><i></i></div><strong><?= e($count) ?> clics</strong></div><?php endforeach; ?></div><div class="panel"><h2>Más consultados por WhatsApp</h2><?php foreach(array_slice($waTop,0,8,true) as $id=>$count): $p=$productMap[$id]??[]; $cat=($p['categorias'][0]??'Sin categoría'); ?><div class="stat-line"><span><?= e($p['titulo'] ?? ('Producto #'.$id)) ?> <small>#<?= e($id) ?> · <?= e($cat) ?></small></span><strong><?= e($count) ?> WhatsApp</strong></div><?php endforeach; if(!$waTop): ?><p class="muted">No hay datos suficientes todavía.</p><?php endif; ?></div></div>
