<?php
$productMap=[]; foreach($productos as $p)$productMap[(string)$p['id']]=$p;
$eventProductId=function($e){$payload=is_array($e['payload']??null)?$e['payload']:json_decode((string)($e['payload']??'{}'),true); return is_array($payload)?(string)($payload['producto_id']??$payload['id_producto']??$payload['product_id']??$payload['id']??''):'';};
$views=array_filter($eventos,fn($e)=>($e['type']??'')==='view_product' && isset($productMap[$eventProductId($e)]));
$wa=array_filter($eventos,fn($e)=>($e['type']??'')==='click_whatsapp' && isset($productMap[$eventProductId($e)]));
$catsEv=array_filter($eventos,fn($e)=>($e['type']??'')==='view_category');
$top=[]; foreach($views as $e){$id=$eventProductId($e); if($id!=='')$top[$id]=($top[$id]??0)+1;} arsort($top);
$waTop=[]; foreach($wa as $e){$id=$eventProductId($e); if($id!=='')$waTop[$id]=($waTop[$id]??0)+1;} arsort($waTop);
?>
<section class="page-head"><div><h1>Métricas</h1><p>Actividad real del catálogo: solo productos existentes, clics y consultas WhatsApp.</p></div><div class="page-actions"><?php if(!empty($orphanCount)): ?><form method="post" action="<?= site_url('admin/metricas/limpiar-huerfanas') ?>" data-confirm-title="Confirmar limpieza" data-confirm-message="Se eliminarán solo eventos vinculados a productos inexistentes. ¿Continuar?" data-confirm-ok="Sí, limpiar"><?= csrf_field() ?><button class="btn outline">Limpiar métricas huérfanas (<?= e($orphanCount) ?>)</button></form><?php endif; ?><form method="post" action="<?= site_url('admin/metricas/resetear') ?>" data-confirm-title="Resetear métricas" data-confirm-message="Esta acción eliminará de forma permanente los clics, visitas y consultas registradas para métricas del catálogo. Los productos, pedidos y ventas no se eliminarán. Después del reset, los productos destacados se volverán a calcular desde cero. ¿Deseás continuar?" data-confirm-ok="Sí, resetear métricas"><?= csrf_field() ?><button class="btn outline">Resetear métricas</button></form></div></section>
<div class="kpi-grid"><div class="kpi"><span>Vistas de productos</span><strong><?= count($views) ?></strong></div><div class="kpi"><span>Clicks WhatsApp</span><strong><?= count($wa) ?></strong></div><div class="kpi"><span>Categorías vistas</span><strong><?= count($catsEv) ?></strong></div><div class="kpi"><span>Eventos huérfanos</span><strong><?= e($orphanCount ?? 0) ?></strong></div></div>
<div class="chart-panel"><div class="panel"><h2>Top productos por interés</h2><?php if(!$top): ?><p class="muted">No hay datos suficientes todavía.</p><?php endif; ?><?php foreach(array_slice($top,0,10,true) as $id=>$count): $p=$productMap[$id]; $cat=($p['categorias'][0]??'Sin categoría'); ?><div class="bar-row product-metric"><img src="<?= e($p['portada'] ?: asset_url('img/logo.png')) ?>" alt=""><span><?= e($p['titulo'] ?? ('Producto #'.$id)) ?><small>#<?= e($id) ?> · <?= e($cat) ?></small></span><div><i></i></div><strong><?= e($count) ?> clics</strong></div><?php endforeach; ?></div><div class="panel"><h2>Más consultados por WhatsApp</h2><?php foreach(array_slice($waTop,0,8,true) as $id=>$count): $p=$productMap[$id]; $cat=($p['categorias'][0]??'Sin categoría'); ?><div class="stat-line"><span><?= e($p['titulo'] ?? ('Producto #'.$id)) ?> <small>#<?= e($id) ?> · <?= e($cat) ?></small></span><strong><?= e($count) ?> WhatsApp</strong></div><?php endforeach; if(!$waTop): ?><p class="muted">No hay datos suficientes todavía.</p><?php endif; ?></div></div>
