<?php
$vis=count(array_filter($productos,fn($p)=>!empty($p['visible'])));$occ=count($productos)-$vis;$sinFoto=count(array_filter($productos,fn($p)=>empty($p['portada'])));$porCat=[]; foreach($productos as $p){foreach(($p['categorias']?:['Sin categoría']) as $c)$porCat[$c]=($porCat[$c]??0)+1;} arsort($porCat); $sinPrecio=array_filter($productos,fn($p)=>(float)($p['precio']??$p['precio_venta']??0)<=0); $ocultos=array_filter($productos,fn($p)=>empty($p['visible']));
$productMap=[]; foreach($productos as $p)$productMap[(string)$p['id']]=$p;
$eventProductId=function($e){$payload=is_array($e['payload']??null)?$e['payload']:json_decode((string)($e['payload']??'{}'),true); return is_array($payload)?(string)($payload['producto_id']??$payload['id_producto']??$payload['product_id']??((in_array(($e['type']??''),['view_product','click_whatsapp'],true))?($payload['id']??''):'') ):'';};
$top=[];$waTop=[]; foreach(($eventos??[]) as $e){$id=$eventProductId($e); if($id===''||!isset($productMap[$id]))continue; if(($e['type']??'')==='view_product')$top[$id]=($top[$id]??0)+1; if(($e['type']??'')==='click_whatsapp')$waTop[$id]=($waTop[$id]??0)+1;} arsort($top); arsort($waTop);
?>
<section class="page-head"><div><h1>Estadísticas</h1><p>Resumen claro de productos, visibilidad, fotos, categorías y consultas reales.</p></div></section>
<div class="kpi-grid"><div class="kpi"><span>Productos totales</span><strong><?= count($productos) ?></strong></div><div class="kpi"><span>Visibles</span><strong><?= $vis ?></strong></div><div class="kpi"><span>Ocultos</span><strong><?= $occ ?></strong></div><div class="kpi"><span>Sin foto</span><strong><?= $sinFoto ?></strong></div><div class="kpi"><span>Categorías activas</span><strong><?= count($categorias) ?></strong></div></div>
<div class="chart-panel"><div class="panel"><h2>Productos por categoría</h2><?php if(!$porCat): ?><p class="muted">No hay datos suficientes todavía.</p><?php endif; ?><?php foreach($porCat as $cat=>$count): ?><div class="stat-line"><span><?= e($cat) ?></span><strong><?= $count ?></strong></div><?php endforeach; ?></div><div class="panel"><h2>Alertas del catálogo</h2><div class="stat-list"><div class="stat-line"><span>Productos sin precio</span><strong><?= count($sinPrecio) ?></strong></div><div class="stat-line"><span>Productos ocultos</span><strong><?= count($ocultos) ?></strong></div><div class="stat-line"><span>Productos sin foto</span><strong><?= $sinFoto ?></strong></div></div></div></div>
<div class="chart-panel"><div class="panel"><h2>Productos más vistos</h2><?php if(!$top): ?><p class="muted">No hay datos suficientes todavía.</p><?php endif; ?><?php foreach(array_slice($top,0,6,true) as $id=>$count): $p=$productMap[$id]; $cat=$p['categorias'][0]??'Sin categoría'; ?><div class="bar-row product-metric"><img src="<?= e($p['portada'] ?: asset_url('img/logo.png')) ?>" alt=""><span><?= e($p['titulo'] ?? '-') ?><small>#<?= e($id) ?> · <?= e($cat) ?></small></span><strong><?= e($count) ?> clics</strong></div><?php endforeach; ?></div><div class="panel"><h2>Consultas WhatsApp</h2><?php if(!$waTop): ?><p class="muted">No hay datos suficientes todavía.</p><?php endif; ?><?php foreach(array_slice($waTop,0,6,true) as $id=>$count): $p=$productMap[$id]; $cat=$p['categorias'][0]??'Sin categoría'; ?><div class="stat-line"><span><?= e($p['titulo'] ?? '-') ?> <small>#<?= e($id) ?> · <?= e($cat) ?></small></span><strong><?= e($count) ?> WhatsApp</strong></div><?php endforeach; ?></div></div>
